import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '@/app/contexts/ThemeContext';
import { GitHubLink } from "@/components/github-link";

export const metadata: Metadata = {
  title: "JournalAPP",
  description: "Generated by Bibek",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <GitHubLink />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}